# Generated by Django 4.0.4 on 2022-07-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_order_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='days_for_rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='loc_from',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='loc_to',
            field=models.CharField(default='', max_length=50),
        ),
    ]
